### PR TITLE
Merge upstream

### PR DESCRIPTION
**Pull request by MuhistheHolvi**
Add support for:
German tax number.
Estonian Registerikood.
The Estonian registration code is already implemented in our branch holvi-master abut the file was renamed upstream and more validation logic implemented by the author.

### CODE REVIEW

**Comment by harrastia** [comment]
I see files come in full, I thought these were contributions made by us (I was expecting changes to already existing files), has the author changed the name of files? will we have to remove some of ours we have already merged to our master?

**Comment by MuhistheHolvi** [comment]
@harrastia Yes, you can see in the author comment. He have changed the file name and added more validation logic. We have to remove holvi-master files in a later PR. The files in question is not used yet.

**Comment by harrastia** [comment]
Ok, next time mention that in the description as well

**Review by harrastia — APPROVED** [review]
This is good, but let's remember to remove the sources which have been renamed to avoid duplicated code

**Comment by arthurdejong** [comment]
Hi,

First of all: thanks for making your improvements to python-stdnum available on Github. It is always nice to see your software get used in other applications and even nicer if companies can provide  improvements back to Open Source projects.

I've had a quick look to see the differences between holvi-master and python-stdnum master:

- There are minor differences in `stdnum.at.businessid` (some comment differences and the addition of `luhn` and `AUSTRIAN_COURTS` which don't seem to be used.
- There are minor differences in `stdnum.fi.ytunnus` (mainly the use of clean that takes care of some nasty corner cases for a lot of numbers, the returning of a compact representation in `validate()` and the introduction of a `format()` function).
- The holvi-master branch has `stdnum.de.handelsregisternummer` that I haven't merged yet. The main reason for that is that it is a bit difficult to get more background info on it. That the state is part of the number is also a bit ugly.
- The holvi-master branch has both `stdnum.de.steueridentifikationsnummer` and `stdnum.de.idnr` which should be same (the latter is also in python-stdnum)
- The holvi-master branch has `stdnum.de.stnr` which I have not merged yet into python-stdnum.
- The holvi-master branch has both `stdnum.ee.registrikoodi` and `stdnum.ee.registrikood` which should be same (the latter is also in python-stdnum). I'm not absolutely positive that the i at the end should not be there but I think I found more usage online  without the i if the word was used by itself (I'm happy to be corrected though).
- The `stdnum.isl` package is named `stdnum.is_` in python-stdnum because that follows a convention I've seen in some other projects that use country codes. In the implementations there are only a few minor differences but they should be functionally equal.
- There are only a few other minor differences between modules (some aliases, some docstring differences, etc.)

Again thanks for providing these numbers.

**Pull request merged**
